/* tslint:disable */
/* eslint-disable */
/**
 * Ragagent MCP Gateway
 * Advanced AI-powered conversation management system
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  RagagentRagatangaFlowsFlowWebhookHandlerEncryptedFlowData,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    RagagentRagatangaFlowsFlowWebhookHandlerEncryptedFlowDataFromJSON,
    RagagentRagatangaFlowsFlowWebhookHandlerEncryptedFlowDataToJSON,
} from '../models/index';

export interface FrequenciaPremiadaWebhookFlowsFrequenciaPremiadaWebhookPostRequest {
    ragagentRagatangaFlowsFlowWebhookHandlerEncryptedFlowData?: RagagentRagatangaFlowsFlowWebhookHandlerEncryptedFlowData;
}

/**
 * 
 */
export class WhatsappFlowApi extends runtime.BaseAPI {

    /**
     * Webhook endpoint for WhatsApp Flow Frequencia Premiada.  This implementation is for development and testing purposes. It doesn\'t actually decrypt the data, but returns valid responses.
     * Frequencia Premiada Webhook
     */
    async frequenciaPremiadaWebhookFlowsFrequenciaPremiadaWebhookPostRaw(requestParameters: FrequenciaPremiadaWebhookFlowsFrequenciaPremiadaWebhookPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/flows/frequencia-premiada/webhook`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RagagentRagatangaFlowsFlowWebhookHandlerEncryptedFlowDataToJSON(requestParameters['ragagentRagatangaFlowsFlowWebhookHandlerEncryptedFlowData']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Webhook endpoint for WhatsApp Flow Frequencia Premiada.  This implementation is for development and testing purposes. It doesn\'t actually decrypt the data, but returns valid responses.
     * Frequencia Premiada Webhook
     */
    async frequenciaPremiadaWebhookFlowsFrequenciaPremiadaWebhookPost(requestParameters: FrequenciaPremiadaWebhookFlowsFrequenciaPremiadaWebhookPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.frequenciaPremiadaWebhookFlowsFrequenciaPremiadaWebhookPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
