/* tslint:disable */
/* eslint-disable */
/**
 * Ragagent MCP Gateway
 * Advanced AI-powered conversation management system
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Data structure for abandoned WABA signup flow.
 * @export
 * @interface AbandonedSignupData
 */
export interface AbandonedSignupData {
    /**
     * Screen where customer abandoned the flow
     * @type {string}
     * @memberof AbandonedSignupData
     */
    currentStep: string;
}

/**
 * Check if a given object implements the AbandonedSignupData interface.
 */
export function instanceOfAbandonedSignupData(value: object): value is AbandonedSignupData {
    if (!('currentStep' in value) || value['currentStep'] === undefined) return false;
    return true;
}

export function AbandonedSignupDataFromJSON(json: any): AbandonedSignupData {
    return AbandonedSignupDataFromJSONTyped(json, false);
}

export function AbandonedSignupDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AbandonedSignupData {
    if (json == null) {
        return json;
    }
    return {
        
        'currentStep': json['current_step'],
    };
}

export function AbandonedSignupDataToJSON(json: any): AbandonedSignupData {
    return AbandonedSignupDataToJSONTyped(json, false);
}

export function AbandonedSignupDataToJSONTyped(value?: AbandonedSignupData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current_step': value['currentStep'],
    };
}

