/* tslint:disable */
/* eslint-disable */
/**
 * Ragagent MCP Gateway
 * Advanced AI-powered conversation management system
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Encrypted flow data from WhatsApp Flow webhook.
 * 
 * WhatsApp Flow sends encrypted data in this format when using the data_exchange component.
 * This model represents the raw encrypted data that needs to be decrypted using the
 * private key associated with the public key provided during flow configuration.
 * @export
 * @interface RagagentModelsFlowWebhookEncryptedFlowData
 */
export interface RagagentModelsFlowWebhookEncryptedFlowData {
    /**
     * 
     * @type {string}
     * @memberof RagagentModelsFlowWebhookEncryptedFlowData
     */
    encryptedFlowData: string;
    /**
     * 
     * @type {string}
     * @memberof RagagentModelsFlowWebhookEncryptedFlowData
     */
    encryptedAesKey: string;
    /**
     * 
     * @type {string}
     * @memberof RagagentModelsFlowWebhookEncryptedFlowData
     */
    initialVector: string;
}

/**
 * Check if a given object implements the RagagentModelsFlowWebhookEncryptedFlowData interface.
 */
export function instanceOfRagagentModelsFlowWebhookEncryptedFlowData(value: object): value is RagagentModelsFlowWebhookEncryptedFlowData {
    if (!('encryptedFlowData' in value) || value['encryptedFlowData'] === undefined) return false;
    if (!('encryptedAesKey' in value) || value['encryptedAesKey'] === undefined) return false;
    if (!('initialVector' in value) || value['initialVector'] === undefined) return false;
    return true;
}

export function RagagentModelsFlowWebhookEncryptedFlowDataFromJSON(json: any): RagagentModelsFlowWebhookEncryptedFlowData {
    return RagagentModelsFlowWebhookEncryptedFlowDataFromJSONTyped(json, false);
}

export function RagagentModelsFlowWebhookEncryptedFlowDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RagagentModelsFlowWebhookEncryptedFlowData {
    if (json == null) {
        return json;
    }
    return {
        
        'encryptedFlowData': json['encrypted_flow_data'],
        'encryptedAesKey': json['encrypted_aes_key'],
        'initialVector': json['initial_vector'],
    };
}

export function RagagentModelsFlowWebhookEncryptedFlowDataToJSON(json: any): RagagentModelsFlowWebhookEncryptedFlowData {
    return RagagentModelsFlowWebhookEncryptedFlowDataToJSONTyped(json, false);
}

export function RagagentModelsFlowWebhookEncryptedFlowDataToJSONTyped(value?: RagagentModelsFlowWebhookEncryptedFlowData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'encrypted_flow_data': value['encryptedFlowData'],
        'encrypted_aes_key': value['encryptedAesKey'],
        'initial_vector': value['initialVector'],
    };
}

