/* tslint:disable */
/* eslint-disable */
/**
 * Ragagent MCP Gateway
 * Advanced AI-powered conversation management system
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Encrypted flow data from WhatsApp webhook.
 * @export
 * @interface RagagentRagatangaFlowsFlowWebhookHandlerEncryptedFlowData
 */
export interface RagagentRagatangaFlowsFlowWebhookHandlerEncryptedFlowData {
    /**
     * 
     * @type {string}
     * @memberof RagagentRagatangaFlowsFlowWebhookHandlerEncryptedFlowData
     */
    encryptedFlowData: string;
    /**
     * 
     * @type {string}
     * @memberof RagagentRagatangaFlowsFlowWebhookHandlerEncryptedFlowData
     */
    encryptedAesKey: string;
    /**
     * 
     * @type {string}
     * @memberof RagagentRagatangaFlowsFlowWebhookHandlerEncryptedFlowData
     */
    initialVector: string;
}

/**
 * Check if a given object implements the RagagentRagatangaFlowsFlowWebhookHandlerEncryptedFlowData interface.
 */
export function instanceOfRagagentRagatangaFlowsFlowWebhookHandlerEncryptedFlowData(value: object): value is RagagentRagatangaFlowsFlowWebhookHandlerEncryptedFlowData {
    if (!('encryptedFlowData' in value) || value['encryptedFlowData'] === undefined) return false;
    if (!('encryptedAesKey' in value) || value['encryptedAesKey'] === undefined) return false;
    if (!('initialVector' in value) || value['initialVector'] === undefined) return false;
    return true;
}

export function RagagentRagatangaFlowsFlowWebhookHandlerEncryptedFlowDataFromJSON(json: any): RagagentRagatangaFlowsFlowWebhookHandlerEncryptedFlowData {
    return RagagentRagatangaFlowsFlowWebhookHandlerEncryptedFlowDataFromJSONTyped(json, false);
}

export function RagagentRagatangaFlowsFlowWebhookHandlerEncryptedFlowDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RagagentRagatangaFlowsFlowWebhookHandlerEncryptedFlowData {
    if (json == null) {
        return json;
    }
    return {
        
        'encryptedFlowData': json['encrypted_flow_data'],
        'encryptedAesKey': json['encrypted_aes_key'],
        'initialVector': json['initial_vector'],
    };
}

export function RagagentRagatangaFlowsFlowWebhookHandlerEncryptedFlowDataToJSON(json: any): RagagentRagatangaFlowsFlowWebhookHandlerEncryptedFlowData {
    return RagagentRagatangaFlowsFlowWebhookHandlerEncryptedFlowDataToJSONTyped(json, false);
}

export function RagagentRagatangaFlowsFlowWebhookHandlerEncryptedFlowDataToJSONTyped(value?: RagagentRagatangaFlowsFlowWebhookHandlerEncryptedFlowData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'encrypted_flow_data': value['encryptedFlowData'],
        'encrypted_aes_key': value['encryptedAesKey'],
        'initial_vector': value['initialVector'],
    };
}

