/* tslint:disable */
/* eslint-disable */
/**
 * Ragagent MCP Gateway
 * Advanced AI-powered conversation management system
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Data structure for successful WABA signup completion.
 * @export
 * @interface SuccessfulSignupData
 */
export interface SuccessfulSignupData {
    /**
     * Customer's business phone number ID
     * @type {string}
     * @memberof SuccessfulSignupData
     */
    phoneNumberId: string;
    /**
     * Customer's WhatsApp Business Account ID
     * @type {string}
     * @memberof SuccessfulSignupData
     */
    wabaId: string;
    /**
     * Customer's business portfolio ID
     * @type {string}
     * @memberof SuccessfulSignupData
     */
    businessId: string;
}

/**
 * Check if a given object implements the SuccessfulSignupData interface.
 */
export function instanceOfSuccessfulSignupData(value: object): value is SuccessfulSignupData {
    if (!('phoneNumberId' in value) || value['phoneNumberId'] === undefined) return false;
    if (!('wabaId' in value) || value['wabaId'] === undefined) return false;
    if (!('businessId' in value) || value['businessId'] === undefined) return false;
    return true;
}

export function SuccessfulSignupDataFromJSON(json: any): SuccessfulSignupData {
    return SuccessfulSignupDataFromJSONTyped(json, false);
}

export function SuccessfulSignupDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessfulSignupData {
    if (json == null) {
        return json;
    }
    return {
        
        'phoneNumberId': json['phone_number_id'],
        'wabaId': json['waba_id'],
        'businessId': json['business_id'],
    };
}

export function SuccessfulSignupDataToJSON(json: any): SuccessfulSignupData {
    return SuccessfulSignupDataToJSONTyped(json, false);
}

export function SuccessfulSignupDataToJSONTyped(value?: SuccessfulSignupData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phone_number_id': value['phoneNumberId'],
        'waba_id': value['wabaId'],
        'business_id': value['businessId'],
    };
}

