/* tslint:disable */
/* eslint-disable */
/**
 * Ragagent MCP Gateway
 * Advanced AI-powered conversation management system
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UIEventRequest
 */
export interface UIEventRequest {
    /**
     * 
     * @type {string}
     * @memberof UIEventRequest
     */
    tenantId: string;
    /**
     * 
     * @type {string}
     * @memberof UIEventRequest
     */
    userPrompt: string;
    /**
     * 
     * @type {string}
     * @memberof UIEventRequest
     */
    conversationId?: string;
    /**
     * 
     * @type {string}
     * @memberof UIEventRequest
     */
    source?: string;
    /**
     * 
     * @type {string}
     * @memberof UIEventRequest
     */
    requestId?: string;
}

/**
 * Check if a given object implements the UIEventRequest interface.
 */
export function instanceOfUIEventRequest(value: object): value is UIEventRequest {
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('userPrompt' in value) || value['userPrompt'] === undefined) return false;
    return true;
}

export function UIEventRequestFromJSON(json: any): UIEventRequest {
    return UIEventRequestFromJSONTyped(json, false);
}

export function UIEventRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UIEventRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'tenantId': json['tenant_id'],
        'userPrompt': json['user_prompt'],
        'conversationId': json['conversation_id'] == null ? undefined : json['conversation_id'],
        'source': json['source'] == null ? undefined : json['source'],
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
    };
}

export function UIEventRequestToJSON(json: any): UIEventRequest {
    return UIEventRequestToJSONTyped(json, false);
}

export function UIEventRequestToJSONTyped(value?: UIEventRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tenant_id': value['tenantId'],
        'user_prompt': value['userPrompt'],
        'conversation_id': value['conversationId'],
        'source': value['source'],
        'request_id': value['requestId'],
    };
}

