/* tslint:disable */
/* eslint-disable */
/**
 * Ragagent MCP Gateway
 * Advanced AI-powered conversation management system
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to exchange authorization code for access token.
 * @export
 * @interface WABATokenExchangeRequest
 */
export interface WABATokenExchangeRequest {
    /**
     * 
     * @type {string}
     * @memberof WABATokenExchangeRequest
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof WABATokenExchangeRequest
     */
    clientSecret: string;
    /**
     * 
     * @type {string}
     * @memberof WABATokenExchangeRequest
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof WABATokenExchangeRequest
     */
    redirectUri?: string | null;
}

/**
 * Check if a given object implements the WABATokenExchangeRequest interface.
 */
export function instanceOfWABATokenExchangeRequest(value: object): value is WABATokenExchangeRequest {
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('clientSecret' in value) || value['clientSecret'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function WABATokenExchangeRequestFromJSON(json: any): WABATokenExchangeRequest {
    return WABATokenExchangeRequestFromJSONTyped(json, false);
}

export function WABATokenExchangeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WABATokenExchangeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['client_id'],
        'clientSecret': json['client_secret'],
        'code': json['code'],
        'redirectUri': json['redirect_uri'] == null ? undefined : json['redirect_uri'],
    };
}

export function WABATokenExchangeRequestToJSON(json: any): WABATokenExchangeRequest {
    return WABATokenExchangeRequestToJSONTyped(json, false);
}

export function WABATokenExchangeRequestToJSONTyped(value?: WABATokenExchangeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_id': value['clientId'],
        'client_secret': value['clientSecret'],
        'code': value['code'],
        'redirect_uri': value['redirectUri'],
    };
}

