/* tslint:disable */
/* eslint-disable */
/**
 * Ragagent MCP Gateway
 * Advanced AI-powered conversation management system
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response from Facebook token exchange.
 * @export
 * @interface WABATokenExchangeResponse
 */
export interface WABATokenExchangeResponse {
    /**
     * 
     * @type {string}
     * @memberof WABATokenExchangeResponse
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof WABATokenExchangeResponse
     */
    tokenType?: string;
    /**
     * 
     * @type {number}
     * @memberof WABATokenExchangeResponse
     */
    expiresIn?: number | null;
}

/**
 * Check if a given object implements the WABATokenExchangeResponse interface.
 */
export function instanceOfWABATokenExchangeResponse(value: object): value is WABATokenExchangeResponse {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    return true;
}

export function WABATokenExchangeResponseFromJSON(json: any): WABATokenExchangeResponse {
    return WABATokenExchangeResponseFromJSONTyped(json, false);
}

export function WABATokenExchangeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WABATokenExchangeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
        'tokenType': json['token_type'] == null ? undefined : json['token_type'],
        'expiresIn': json['expires_in'] == null ? undefined : json['expires_in'],
    };
}

export function WABATokenExchangeResponseToJSON(json: any): WABATokenExchangeResponse {
    return WABATokenExchangeResponseToJSONTyped(json, false);
}

export function WABATokenExchangeResponseToJSONTyped(value?: WABATokenExchangeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
        'token_type': value['tokenType'],
        'expires_in': value['expiresIn'],
    };
}

