/* tslint:disable */
/* eslint-disable */
/**
 * Ragagent MCP Gateway
 * Advanced AI-powered conversation management system
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SignupData } from './SignupData';
import {
    SignupDataFromJSON,
    SignupDataFromJSONTyped,
    SignupDataToJSON,
    SignupDataToJSONTyped,
} from './SignupData';

/**
 * Request to complete WABA signup process.
 * @export
 * @interface WABASignupCompleteRequest
 */
export interface WABASignupCompleteRequest {
    /**
     * 
     * @type {string}
     * @memberof WABASignupCompleteRequest
     */
    tenantId: string;
    /**
     * 
     * @type {string}
     * @memberof WABASignupCompleteRequest
     */
    authCode: string;
    /**
     * 
     * @type {SignupData}
     * @memberof WABASignupCompleteRequest
     */
    signupData: SignupData;
    /**
     * 
     * @type {string}
     * @memberof WABASignupCompleteRequest
     */
    sessionId?: string | null;
}

/**
 * Check if a given object implements the WABASignupCompleteRequest interface.
 */
export function instanceOfWABASignupCompleteRequest(value: object): value is WABASignupCompleteRequest {
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('authCode' in value) || value['authCode'] === undefined) return false;
    if (!('signupData' in value) || value['signupData'] === undefined) return false;
    return true;
}

export function WABASignupCompleteRequestFromJSON(json: any): WABASignupCompleteRequest {
    return WABASignupCompleteRequestFromJSONTyped(json, false);
}

export function WABASignupCompleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WABASignupCompleteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'tenantId': json['tenant_id'],
        'authCode': json['auth_code'],
        'signupData': SignupDataFromJSON(json['signup_data']),
        'sessionId': json['session_id'] == null ? undefined : json['session_id'],
    };
}

export function WABASignupCompleteRequestToJSON(json: any): WABASignupCompleteRequest {
    return WABASignupCompleteRequestToJSONTyped(json, false);
}

export function WABASignupCompleteRequestToJSONTyped(value?: WABASignupCompleteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tenant_id': value['tenantId'],
        'auth_code': value['authCode'],
        'signup_data': SignupDataToJSON(value['signupData']),
        'session_id': value['sessionId'],
    };
}

