/* tslint:disable */
/* eslint-disable */
/**
 * Ragagent MCP Gateway
 * Advanced AI-powered conversation management system
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response with signup session configuration.
 * @export
 * @interface WABASignupSessionResponse
 */
export interface WABASignupSessionResponse {
    /**
     * 
     * @type {string}
     * @memberof WABASignupSessionResponse
     */
    appId: string;
    /**
     * 
     * @type {string}
     * @memberof WABASignupSessionResponse
     */
    configurationId: string;
    /**
     * 
     * @type {string}
     * @memberof WABASignupSessionResponse
     */
    graphApiVersion: string;
    /**
     * 
     * @type {string}
     * @memberof WABASignupSessionResponse
     */
    featureType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WABASignupSessionResponse
     */
    redirectUri?: string | null;
}

/**
 * Check if a given object implements the WABASignupSessionResponse interface.
 */
export function instanceOfWABASignupSessionResponse(value: object): value is WABASignupSessionResponse {
    if (!('appId' in value) || value['appId'] === undefined) return false;
    if (!('configurationId' in value) || value['configurationId'] === undefined) return false;
    if (!('graphApiVersion' in value) || value['graphApiVersion'] === undefined) return false;
    return true;
}

export function WABASignupSessionResponseFromJSON(json: any): WABASignupSessionResponse {
    return WABASignupSessionResponseFromJSONTyped(json, false);
}

export function WABASignupSessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WABASignupSessionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['app_id'],
        'configurationId': json['configuration_id'],
        'graphApiVersion': json['graph_api_version'],
        'featureType': json['feature_type'] == null ? undefined : json['feature_type'],
        'redirectUri': json['redirect_uri'] == null ? undefined : json['redirect_uri'],
    };
}

export function WABASignupSessionResponseToJSON(json: any): WABASignupSessionResponse {
    return WABASignupSessionResponseToJSONTyped(json, false);
}

export function WABASignupSessionResponseToJSONTyped(value?: WABASignupSessionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_id': value['appId'],
        'configuration_id': value['configurationId'],
        'graph_api_version': value['graphApiVersion'],
        'feature_type': value['featureType'],
        'redirect_uri': value['redirectUri'],
    };
}

