/* tslint:disable */
/* eslint-disable */
/**
 * Ragagent MCP Gateway
 * Advanced AI-powered conversation management system
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response after completing WABA signup.
 * @export
 * @interface WABASignupCompleteResponse
 */
export interface WABASignupCompleteResponse {
    /**
     * 
     * @type {boolean}
     * @memberof WABASignupCompleteResponse
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof WABASignupCompleteResponse
     */
    wabaId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WABASignupCompleteResponse
     */
    phoneNumberId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WABASignupCompleteResponse
     */
    businessId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WABASignupCompleteResponse
     */
    accessToken?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WABASignupCompleteResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the WABASignupCompleteResponse interface.
 */
export function instanceOfWABASignupCompleteResponse(value: object): value is WABASignupCompleteResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function WABASignupCompleteResponseFromJSON(json: any): WABASignupCompleteResponse {
    return WABASignupCompleteResponseFromJSONTyped(json, false);
}

export function WABASignupCompleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WABASignupCompleteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'wabaId': json['waba_id'] == null ? undefined : json['waba_id'],
        'phoneNumberId': json['phone_number_id'] == null ? undefined : json['phone_number_id'],
        'businessId': json['business_id'] == null ? undefined : json['business_id'],
        'accessToken': json['access_token'] == null ? undefined : json['access_token'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function WABASignupCompleteResponseToJSON(json: any): WABASignupCompleteResponse {
    return WABASignupCompleteResponseToJSONTyped(json, false);
}

export function WABASignupCompleteResponseToJSONTyped(value?: WABASignupCompleteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'waba_id': value['wabaId'],
        'phone_number_id': value['phoneNumberId'],
        'business_id': value['businessId'],
        'access_token': value['accessToken'],
        'error': value['error'],
    };
}

